version: "3.9"
services:
  instasaw_api:
    #  it depends on the postgres and redis
    depends_on:
      - postgres_db
      - redis_db
    build:
      # location of the project in our folder
      context: .
      dockerfile: Dockerfile
    #  the name of the image
    image: instasaw_api
    # my env file
    environment:
      - PORT=8000
    volumes:
      - staticfiles:/staticfiles
    env_file:
      - .env
    expose:
      - 8001
    ports:
      - "8001:8000"
    command: sh -c "sh /app/migrate.sh && sh /app/daphne_entrypoint.sh"

  postgres_db:
    image: postgres
    restart: always
    env_file:
      - .env
    command: -p 5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis_db:
    image: redis
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6379

  celery:
    env_file:
      - .env
    build: 
      context: .
    depends_on:
      - redis_db
      - postgres_db
      - instasaw_api
    command: sh -c "chmod +x  /app/celery_command.sh && sh /app/celery_command.sh"
 
  celery_schedule:
    env_file:
      - .env
    build: 
      context: .
    depends_on:
      - redis_db
      - instasaw_api
      - postgres_db
    command: sh -c "chmod +x  /app/celery_schedule_command.sh && sh /app/celery_schedule_command.sh"
    

volumes:
  postgres_data:
  redis_data:
  staticfiles:



