apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec:
  replicas: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: nginx-deployment