# Generated by Django 4.0.7 on 2022-09-14 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000)),
                ('ledger_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=50)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
